[package]
name = "reddit-tui"
version = "0.1.0"
authors = ["Xithrius <xithrius@gmail.com>"]
edition = "2018"
description = "Reddit in the terminal."
documentation = "https://github.com/Xithrius/reddit-tui"
homepage = "https://github.com/Xithrius/reddit-tui"
repository = "https://github.com/Xithrius/reddit-tui"
license = "MIT OR Apache-2.0"
keywords = ["tui", "reddit"]
categories = ["command-line-utilities"]

[dependencies]
crossterm = "0.22.1"
tui = { version = "0.16.0", default-features = false, features = ['crossterm'] }
anyhow = "1.0.45"
rand = "0.8.4"
unicode-width = "0.1.9"
futures = "0.3.17"
tokio = { version = "1.13.0", features = ["full"] }
reqwest = { version = "0.11.6", features = ["json", "multipart"] }
serde_json = "1.0.70"
serde = { version = "1.0.130", features = ["derive"] }
toml = "0.5.8"
chrono = "0.4"
rustyline = "9.0.0"

[[bin]]
bench = false
path = "src/main.rs"
name = "treddit"
