[package]
name = "terminal-reddit"
version = "0.1.0"
edition = "2018"

[dependencies]
crossterm = "0.21.0"
tui = { version = "0.16.0", default-features = false, features = ['crossterm'] }
anyhow = "1.0.44"
rand = "0.8.4"
unicode-width = "0.1.9"
futures = "0.3.17"
tokio = { version = "1.12.0", features = ["full"] }
reqwest = { version = "0.11.4", features = ["json", "multipart"] }
serde_json = "1.0.68"
serde = { version = "1.0.130", features = ["derive"] }
toml = "0.5.8"
chrono = "0.4"

[[bin]]
bench = false
path = "src/main.rs"
name = "treddit"
