[terminal]
# The delay in milliseconds between terminal updates.
tick_delay = 30

[frontend]
# The space between the border and the main window
margin = 0
# If the time and date is to be shown.
date_shown = true
# The format of the date and time outputs. Formats can be found at https://strftime.org/.
date_format = "%a %b %e %T %Y"

[reddit]
# Username of the current person using the program
username = ""
# Password of the user
password = ""
# Client ID of the script application
client_id = ""
# The secret of the script application
client_secret = ""
# The subreddit that the user wants to browse
subreddit = ""
# The status of the browser (top, hot, new, controversial)
status = ""
# The amount of time in which the posts had been made (day, week, month, year, all)
timespan = ""
